name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: ls
        run: ls -la
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}} > result.txt
      - name: Cat result.txt
        run: cat ./result.txt
      - name: Sed
        run: sed 's/version:.*/ $(cat result.txt)/g' Chart.yaml
      - name: Cat Chart.yaml
        run: cat Chart.yaml
        #sed -i '' -e 's/version:/$(cat result.txt)/g' Chart.yaml > Chart2.yaml

