name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      - name: Change tag in chart
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./Chart.yaml"]'
        env:
         version: ${{steps.tag.outputs.tag}}
