name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag with variables
        run: export V=${{steps.tag.outputs.tag}}
      - name: Create local changes
        run: |
          export V=${{steps.tag.outputs.tag}}
          echo $V
          sed -i "s/version:.*/version: $V/g" Chart.yaml
          cat Chart.yaml
          
      - name: Generate Githup App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key:  ${{ secrets.APP_PRIVATE_KEY }}
      - name: Commit files
        run: |
          AUTHOR_NAME=$(git show -s --format='%an' ${{ github.event.inputs.commit }})
          AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.event.inputs.commit }})
          git config --local user.email "${AUTHOR_EMAIL}"
          git config --local user.name "${AUTHOR_NAME}"
          git checkout master
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.bot-token.outputs.token }}
          branch: main
