name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Use tag with variables
        run: export V=${{steps.tag.outputs.tag}}
      - name: Script
        run: |
          echo $V
          sed 's/version:.*/ $V/g' Chart.yaml
          cat Chart.yaml
