name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: ls
        run: ls -la
     # - name: Use tag
     #   run: echo ${{steps.tag.outputs.tag}} > result.txt
      - name: Use tag with variables
        run: export V=${{steps.tag.outputs.tag}}
      - name: print $V
        run: echo $V
     # - name: Cat result.txt
     #   run: cat ./result.txt
      - name: Sed
        run: sed 's/version:.*/ $V/g' Chart.yaml
      - name: Cat Chart.yaml
        run: cat Chart.yaml
