name: Get tag
on:
  push:
    tags:
      - '*'
jobs:
  github_example_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: ls
        run: ls -la
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      - name: Change tag in chart
        run: sed -i 's/version:/version: ${{steps.tag.outputs.tag}}/g' ./Chart.yaml
